# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: ./build.sh

- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - bash: ./build.sh


- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: .\build.ps1
